import { v4 as uuid } from "uuid";
import { format, addDays } from "date-fns";
import { Task } from "./types";

const d = (offset: number): string => format(addDays(new Date(), offset), "yyyy-MM-dd");

const now = new Date().toISOString();

export const buildSampleTasks = (): Task[] => [
  {
    id: uuid(),
    name: "Q3 Brand Campaign Concept",
    description: "Develop creative concept and moodboard for the Q3 brand campaign.",
    department: "Creative",
    status: "In Progress",
    startDate: d(-12),
    endDate: d(3),
    priority: "High",
    assignedPerson: "Layla Haddad",
    notes: "Client wants 3 concept directions by end of week.",
    departmentHistory: [{ department: "Creative", enteredAt: d(-12), leftAt: null }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    name: "Homepage Redesign Mockups",
    description: "Design updated homepage layout for the client's e-commerce site.",
    department: "Design",
    status: "Waiting for Approval",
    startDate: d(-20),
    endDate: d(-2),
    priority: "Urgent",
    assignedPerson: "Omar Nasser",
    notes: "Sent to client for review, awaiting sign-off.",
    departmentHistory: [
      { department: "Creative", enteredAt: d(-20), leftAt: d(-14) },
      { department: "Design", enteredAt: d(-14), leftAt: null },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    name: "Instagram Reels Content Batch",
    description: "Produce 6 short-form reels for the August content calendar.",
    department: "Social Media",
    status: "In Progress",
    startDate: d(-6),
    endDate: d(9),
    priority: "Medium",
    assignedPerson: "Rana Fares",
    notes: "",
    departmentHistory: [{ department: "Social Media", enteredAt: d(-6), leftAt: null }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    name: "Competitor Landscape Analysis",
    description: "Research and summarize competitor positioning for new client pitch.",
    department: "Strategy",
    status: "Completed",
    startDate: d(-30),
    endDate: d(-22),
    priority: "Medium",
    assignedPerson: "Yousef Amiri",
    notes: "Delivered to pitch team, well received.",
    departmentHistory: [{ department: "Strategy", enteredAt: d(-30), leftAt: d(-22) }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    name: "Client Invoice Reconciliation",
    description: "Reconcile Q2 invoices against retainer scope for three accounts.",
    department: "Accounts",
    status: "On Hold",
    startDate: d(-15),
    endDate: d(-1),
    priority: "Low",
    assignedPerson: "Mona Saleh",
    notes: "Paused, waiting on finance export from client.",
    departmentHistory: [{ department: "Accounts", enteredAt: d(-15), leftAt: null }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    name: "Product Video Shoot - Summer Line",
    description: "On-location shoot for the summer product line video assets.",
    department: "Production",
    status: "Not Started",
    startDate: d(2),
    endDate: d(10),
    priority: "High",
    assignedPerson: "Karim Idris",
    notes: "Location and crew confirmed, waiting on wardrobe.",
    departmentHistory: [{ department: "Production", enteredAt: d(2), leftAt: null }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    name: "Client Portal API Integration",
    description: "Integrate the client reporting portal with the analytics API.",
    department: "Development",
    status: "In Progress",
    startDate: d(-9),
    endDate: d(5),
    priority: "Urgent",
    assignedPerson: "Farah Zeidan",
    notes: "Blocked briefly on API credentials, now resolved.",
    departmentHistory: [{ department: "Development", enteredAt: d(-9), leftAt: null }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    name: "Monthly Retainer Performance Review",
    description: "Prepare and present monthly performance review deck to leadership.",
    department: "Management",
    status: "Cancelled",
    startDate: d(-18),
    endDate: d(-16),
    priority: "Low",
    assignedPerson: "Tarek Nasrallah",
    notes: "Merged into quarterly review instead.",
    departmentHistory: [{ department: "Management", enteredAt: d(-18), leftAt: d(-16) }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    name: "Packaging Design Revisions",
    description: "Apply client feedback round 2 to packaging design files.",
    department: "Design",
    status: "In Progress",
    startDate: d(-4),
    endDate: d(-1),
    priority: "High",
    assignedPerson: "Omar Nasser",
    notes: "Overdue - needs to move fast, client is anxious.",
    departmentHistory: [{ department: "Design", enteredAt: d(-4), leftAt: null }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    name: "Social Listening Report - August",
    description: "Compile sentiment and engagement trends for the August report.",
    department: "Strategy",
    status: "Not Started",
    startDate: d(1),
    endDate: d(8),
    priority: "Medium",
    assignedPerson: "Yousef Amiri",
    notes: "",
    departmentHistory: [{ department: "Strategy", enteredAt: d(1), leftAt: null }],
    createdAt: now,
    updatedAt: now,
  },
];
